spring:
  # 配置数据源
  datasource:
    dynamic:
      primary: db1 # 设置默认的数据源或者数据源组,默认值即为master
      datasource:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.101.135.160:3306/mybatisplus_demo?useUnicode=true&characterEncoding=utf-8
          username: root
          password: root
          # hikari
          hikari:
            connection-test-query: SELECT 1
            ## 最小空闲连接数量
            minimum-idle: 5
            ## 连接池最大连接数，默认是10
            maximum-pool-size: 15
            ## 连接池名称
            pool-name: MyHikariCPOfMaster
            ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            ## 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 20000
            ## 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 180000
            ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            auto-commit: true
        db2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.101.135.160:3307/mybatisplus_demo?useUnicode=true&characterEncoding=utf-8
          username: root
          password: root
          # hikari
          hikari:
            connection-test-query: SELECT 1
            ## 最小空闲连接数量
            minimum-idle: 5
            ## 连接池最大连接数，默认是10
            maximum-pool-size: 15
            ## 连接池名称
            pool-name: MyHikariCPOfMaster
            ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            ## 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 20000
            ## 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 180000
            ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            auto-commit: true
  application:
    name: mybatisplus-demo-server

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:ink/bignose/mybatisplus/mapper/xml/*.xml
  # 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: ink.bignose.mybatisplus.project.entity
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8093